### ISSUE TITLE
quick session问题-手机适配

### ISSUE THREAD

**Issue by Xavier0705** [zran-nz/bug#1026]
第一步： 从班级频道下，点击import from - quick session 进入 PPT选择页面

![Image](https://user-images.githubusercontent.com/115767218/209290163-eaebdfc0-f48c-4f4a-8584-813a8a904ae0.png)
https://classcipe.com/v2/my/classSession/1558045919313719298?header=0

第二步：PPT选择页面参考竞品 
第一页分为： Beginning of class, During class, End of class

![Image](https://user-images.githubusercontent.com/115767218/202931280-83d5d294-3dcd-457e-8780-c9449a312f33.png)

第二页为：
![Image](https://user-images.githubusercontent.com/115767218/202931282-509d8d68-f181-4ac3-886d-b0b127a2f3c5.png)

第三页为：自定义的PPT

![Image](https://user-images.githubusercontent.com/115767218/209291193-80b63e23-ba33-4f33-bd0a-a248af9f9088.png)

（竞品Pear deck 登录： alee60757@gmail.com, 密码：Classcipe@123 ）

？ 号内的文字提示：
1.Text: Students will provide text responses to the slide content.
2.Drawing: Students will draw on or leave text on any part of the slide.
3.Multiple choice: Students will select a choice out of A,B,C and D.
4.Comment: Students will leave comments on any part of the slides by marking with a dot.
5.Multimedia: Students will answer question by uploading files from their desktop or recording audios as responses.

Karen10月17日edit：
从班级页面的import按钮进入，点击quick session后弹窗显示所有题型的prompt slide，上方可以用题型筛选Question type，
下方直接展示6张备选slide（均为单张所有不用预览），点击选上后，右下角Start session now，左下角Discard

模板列表接口
`await App.service('templates').get('quickList')`
创建session接口
`await App.service('session').create({ id: 'presation_id', pages: [{_id: 'page.id', url: 'page.url'}, ...], guest: true })'`

模版选择的参考样式

**Comment by luorixin** [comment]
新需求就指给后面的人吧

**Comment by classcipetest** [comment]
Karen补充
1.quick session的第一步-select prompt slides页面
选择new prompt的页面最上方将筛选条件的标签展开显示，对应后台已经在prompt ppt上打好的标签，分两类（不同颜色区分）：
第一类场景：Engage Explore Explain Elaborate Evaluate
第二类题型：Text Multimedia Comment Drawing Multiple Choice(Multiple Choice是一个标签） 
<img width="998" alt="image" src="https://user-images.githubusercontent.com/115767218/202933977-1a14bb25-4f19-4102-92fd-bc10bb60151b.png">
用户点击某个标签后，将该标签相关的PPT置顶显示，外框加粗，并且将该ppt的名称内对应的标签颜色区分显示（如下图）
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/115767218/202934273-3cbe28cf-21bc-416b-851c-d849ff6eb6a0.png">
2.quick session的第二步-reorder prompt slides页面（给所选的slide重新排序）
左侧预览所选slides，右侧拖动排序
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/115767218/202937273-18746576-13bc-4ea7-b462-e5e693a62044.png">

**Comment by classcipetest** [comment]
问号icon（？）的补充说明语言

Engage: Engage students by asking questions of what, why and how and students might reply by entering text and making choices.
Engage: Activating prior knowledge: Engage students by completing the 3-2-1 bridge activity, students might enter text.
Explore: Students explore the topic by answering "What happens when? What did you discover/find out? What happens if? What questions do you have?"
Explore activities: Students will perform investigation, correct information, solve a problem, construct a model and Claim-Support-Question by entering text or comment.
Explain: Students will provide explanations, compare and find differences, use evidences, or provide other explanations by entering text or comment.
Explain activities: Students will answer "What makes you say that?" and conduct think skill activities, including compare and contrast, classify, error analysis by entering text or comment.
Elaborate: Students will elaborate on the characteristics of certain items, discover factors, find solutions to problems by entering text or comment.
Evaluate: Students will evaluate by entering text or comment to questions of "What surprised you? How did you arrive at your solution or conclusion? Did you change any of your initial thinking? What caused you to see things differently? How did you figure out...?
Text: Students will provide text responses to the slide content.
Drawing: Students will draw on or leave text on any part of the slide.
Multiple choice: Students will select a choice out of A,B,C and D.
Comment: Students will leave comments on any part of the slides by marking with a dot.
Multimedia: Students will answer question by uploading files from their desktop or recording audios as responses.

**Comment by eongoo** [comment]
默认选择前三个 Purpose 作为第一页的内容
tag 如果有多个，会合并列出，但是tips只显示第一个tag的文案
